- jhub_apps/service/service.py
- jhub_apps/tests/test_api.py
> Add endpoint for getting frameworks

- jhub_apps/service/service.py
- jhub_apps/service/utils.py
> Add endpoints for conda-environment and spawner profiles

- jhub_apps/service/models.py
- jhub_apps/spawner/spawner_creation.py
- jhub_apps/tests/test_api.py
This add the ability to make app shareable to public (for unauthenticated users).
> Add backend option to public sharing apps

- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/service.py
- jhub_apps/tests/test_api.py
> Add start/stop server endpoints

- jhub_apps/service/app.py
- jhub_apps/service/service.py
- jhub_apps/service/utils.py
- jhub_apps/spawner/types.py
> Use default thumbnails for all apps

- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/service.py
> Fix start server

- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/service.py
- jhub_apps/tests/conftest.py
- jhub_apps/tests/constants.py
- jhub_apps/tests/test_api.py
> Add shared apps in the server response

- jhub_apps/config_utils.py
- jhub_apps/configuration.py
This is useful for k8s deployment
> parameterize hub host

- jhub_apps/service/service.py
> Add username in shared apps

- jhub_apps/service/routes.py
- jhub_apps/service/utils.py
> Send user to conda env callable

- README.md
> Add pip/conda installation instructions in README

- .github/workflows/lint-ui.yml
> Add a check for uncommitted JS files

- environment-dev.yml
- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/app.py
- jhub_apps/service/auth.py
- jhub_apps/service/logging_utils.py
- jhub_apps/service/middlewares.py
- jhub_apps/service/routes.py
- jhub_apps/service/utils.py
- jhub_apps/spawner/spawner_creation.py
- pyproject.toml
> Add structured logging

- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/routes.py
- jhub_apps/service/utils.py
- jhub_apps/spawner/command.py
- jhub_apps/spawner/spawner_creation.py
> Misc fixes, more logging, ready timeout bump

- jhub_apps/spawner/command.py
Set ready timeout back to 300.
> increase timeout

- jhub_apps/themes/__init__.py
> Send version info to template

- jhub_apps/service/models.py
- jhub_apps/tests/test_api.py
> Accept environment variables in the user options API

- .github/workflows/docker.yml
- .github/workflows/lint-ui.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test-ui.yml
- .github/workflows/test.yml
> MAINT: Fix CI warnings

- jhub_apps/service/utils.py
N/A
- Updates to get theme from JupyterHub config template_vars
> Fix JupyterHub Config Theme Retrieval

- .github/workflows/test-integration.yml
- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/routes.py
- jhub_apps/service/utils.py
- jhub_apps/spawner/types.py
- jhub_apps/tests/test_api.py
- jhub_apps/tests_e2e/test_integration.py
- jupyterhub_config.py
There were no tests for when there was server options page.
Fix getting thumbnail from url as the server was calling itself, which was very flaky.
> Add tests for with added server options + fix flaky tests

- .github/workflows/lint.yml
- .github/workflows/test-integration.yml
- .github/workflows/test.yml
> Run CI on main and PR always

- jhub_apps/hub_client/hub_client.py
> Limit server names to within 255 characters

- jhub_apps/spawner/spawner_creation.py
> Add option to configure keep alive from environment variable on app

- .github/workflows/test-integration.yml
- .github/workflows/test.yml
> Test on JupyterHub `5.0.0b1` and bump Python

- jhub_apps/service/routes.py
- jhub_apps/service/utils.py
- jhub_apps/tests/test_api.py
> Fix filtering for shared servers

- jhub_apps/service/routes.py
- jupyterhub_config.py
> Reduce permissions in the example config

- jhub_apps/hub_client/hub_client.py
The bug was causing the token to invalidate by a function down the stack.
> Fix token invalidation by a function down the stack

- jhub_apps/templates/style.css
> Fix JupyterHub 5/App Launcher Styling Issues

- jhub_apps/service/utils.py
- jhub_apps/tests/tests_unit/test_api.py
> Remove duplicate apps for common group

- ui/src/pages/home/apps-section/app-filters/app-filters.test.tsx
N/A
- Fixed test by updating to check for filter count before clicking button
> Fix Flaky Unit Test

- .github/dependabot.yml
This update is intended to group dependabot PRs to simplify patching, such that all patch and minor updates should be grouped in to 1 PR. All major patches should be handled separately. This also includes some exclusions for ongoing MUI patches which currently have issues with this app.
N/A
- Updated to group all patch and minor versions. 
- Added mui dependencies to ignore until issues are resolved.
> Dependabot Grouping Updates

- .github/dependabot.yml
Update to properly group based on update-type.
> Dependabot Grouping Updates - 2

- README.md
Looking at https://github.com/nebari-dev/jhub-apps/pull/355 I noticed that dev install instructions did not include `npm install`
> Add missing `npm install` step

- docs/docs/create-apps/voila-app.md
> Fix typo in the spelling of "voila"

- jhub_apps/templates/style.css
- ui/package-lock.json
> Admin Style Fix

- jhub_apps/hub_client/hub_client.py
- jhub_apps/spawner/types.py
- jhub_apps/tests/tests_e2e/test_api.py
- jhub_apps/tests/tests_e2e/utils.py
> Spinup multiple JupyterLab servers

- jhub_apps/hub_client/hub_client.py
- jhub_apps/service/routes.py
- jhub_apps/tests/tests_e2e/test_api.py
- jhub_apps/tests/tests_e2e/utils.py
- jhub_apps/tests/tests_unit/test_api.py
- jupyterhub_config.py
> Add ability to start shared servers

- README.md
- environment-dev.yml
- pyproject.toml
- environment-dev.yml was missing playwright so I added it.  
- I also added a optional dev dependencies in the pyproject file
- I attempted to synchronize the conda env and the dependencies in the pyproject file.
> tries to fix differences between pyproject and conda env

- environment-dev.yml
- pyproject.toml
Looks like a new version of PyJWT is released https://pypi.org/project/PyJWT/2.10.0/, which is breaking the authentication.
https://github.com/nebari-dev/jhub-apps/actions/runs/11889273170/job/33132013579
Pinning this for now, until we have bandwidth to upgrade to latest PyJWT.
> Pin `PyJWT<2.10.0` to avoid breaking change

- pyproject.toml
> Bump jhsingle-native-proxy to 0.8.3

- .github/workflows/test-integration.yml
- .github/workflows/test.yml
This is specially useful for debugging when something fails in the CI.
Ref: https://docs.pytest.org/en/stable/how-to/logging.html#live-logs
Link: https://github.com/nebari-dev/jhub-apps/actions/runs/12419900985/job/34676259073?pr=446#step:14:29
Link: https://github.com/nebari-dev/jhub-apps/actions/runs/12467273261/job/34796277459?pr=562#step:14:52
> Enable logging while running tests in CI

- docs/docs/configuration.md
Docs related to https://github.com/nebari-dev/jhub-apps/pull/516
> add startup_app docs

- pyproject.toml
> Add missing `312` in `[[tool.hatch.envs.test.matrix]]`

- .github/workflows/test-integration.yml
This PR updates the JupyterHub version in the integration tests workflow matrix to ensure the latest release (5.3.0) is tested.
> Upgrade JupyterHub to version 5.3.0 in the integration tests workflow
